#!/bin/bash -e
if [[ "${1}" == "--debug" ]]; then
  echo "operation: 'list'  (this: $0)"
  "$(which python)" ~/git-tools/git_server.py --debug --command list
  exit $?
else
  "$(which python)" ~/git-tools/git_server.py --command list
  exit $?
fi
