#!/bin/bash -e
if [[ "${2}" == "--debug" ]]; then
  echo "operation: 'create', name: '${1}'  (this: $0)"
  "$(which python)" ~/git-tools/git_server.py --debug --command create --repo "${1}"
  exit $?
else
  "$(which python)" ~/git-tools/git_server.py --command create --repo "${1}"
  exit $?
fi

