#!/bin/bash -e
if [[ "${2}" == "--debug" ]]; then
  "$(which python)" ~/git-tools/git_server.py --debug --command use --server "${1}"
  exit $?
else
  "$(which python)" ~/git-tools/git_server.py --command use --server "${1}"
  exit $?
fi

